# Site settings
title: "TIL: Today I Learned"
initials: "TIL"
phrase: "today i learned"
email: akafred@akafred.com
description: > # this means to ignore newlines until "baseurl:"
  Writings on system development and operations. Stuff I learn.
baseurl: "" # the subpath of your site, e.g. /blog/
exclude: ['deploy_rsa.enc', 'Gemfile.lock', 'Gemfile', 'Makefile']
url: "http://www.akafred.com" # the base hostname & protocol for your site
twitter_username: akafred
github_username:  akafred

permalink: /:year/:month/:title/
# Build settings
markdown: kramdown
