# Site settings
title: "TIL: Today I Learned"
initials: "T I L"
phrase: "TODAY I LEARNED"
email: akafred@akafred.com
description: > # this means to ignore newlines until "baseurl:"
  Writings on system development and operations. Stuff I learn.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.akafred.com" # the base hostname & protocol for your site
twitter_username: akafred
github_username:  akafred

# Build settings
markdown: kramdown

#Default settings
paginate: 6
paginate_path: /page:num/

permalink: /:year/:month/:title/

# Sass style
sass:
  style: compressed

# Comments
disqus-shortname: akafred

#social
# facebook: http://facebook.com/webjeda
# quora: http://quora.com/sharathdt
twitter: http://twitter.com/@akafred
github: http://github.com/akafred


#Plugins
gems:
  - jekyll-paginate
