# Site settings
title: "TIL: Today I Learned"
email: akafred@akafred.com
description: > # this means to ignore newlines until "baseurl:"
  Writings on system development and operations. Stuff I learn.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.akafred.com" # the base hostname & protocol for your site
twitter_username: akafred
github_username:  akafred

permalink: /:year/:month/:title/
# Build settings
markdown: kramdown
